INSERT INTO users (ID, NAME, EMAIL, PASSWORD, CREATED_AT, UPDATED_AT)
VALUES (1, 'stu', 'stu@stu.com', 'password', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO TRAVEL_PLAN (ID, DEPARTURE_DATE, USER_ID, NAME)
VALUES (1, 1750285667, 1, 'Plan');